codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

coverage:
  status:
    patch: off
    project:
      default:
        threshold: 2
        round: down
        target: 30%
      # frontend:
      #   target: 10%
      #   paths: frontend/
