name: Python Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Containers
      run: docker-compose -f "docker-compose-dev.yml" up -d --build

    - name: Run Containers in detach mode
      run: docker-compose -f docker-compose-dev.yaml up --detach
    
    - name: Run pytest
      run: docker ps